version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/SmartPeak
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install curl -y
          curl https://docs.readthedocs.io/en/stable/versions.html > tmpfile
          cp tmpfile /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  publish_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            mkdir bin
            curl https://docs.readthedocs.io/en/stable/versions.html > bin/tmpfile
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} bin

workflows:
  version: 2.1
  build:
    jobs:
      - build_ubuntu:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_release:
          requires:
            - build_ubuntu
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/