version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/SmartPeak
    resource_class: large
    steps:
      - checkout
      - run: |
          apt-get update
  
  build_docs:
    docker:
      - image: ubuntu:20.04
    steps:
      - run: |
          apt-get update

workflows:
  version: 2.1
  build:
    jobs:
      - build_ubuntu
      - build_docs:
          requires:
            - build_ubuntu
          filters:
            tags:
              only: v
            branches:
              only: develop