version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/SmartPeak
    steps:
      - checkout
      - run: |
          echo ${CIRCLE_WORKFLOW_ID}
          CIRCLE_WORKFLOW_ID="${CIRCLE_WORKFLOW_ID}:CIRCLE_BUILD_NUM"
          apt-get update
          apt-get install curl -y
          curl https://docs.readthedocs.io/en/stable/versions.html > tmpfile
          cp tmpfile /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  publish_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            mkdir bin
            curl -H "Circle-Token: ${CIRCLE_TOKEN}" "https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${VERSION}/artifacts?branch=develop&tag=${VERSION}"

workflows:
  version: 2.1
  build:
    jobs:
      - build_ubuntu:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_release:
          requires:
            - build_ubuntu
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/