version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build_ubuntu:
    docker:
      - image: ubuntu:20.04
    working_directory: ~/SmartPeak
    steps:
      - checkout
      - run: |
          echo ${CIRCLE_WORKFLOW_ID}
          apt-get update
          apt-get install curl -y
          curl https://docs.readthedocs.io/en/stable/versions.html > tmpfile
          cp tmpfile /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  publish_release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            mkdir arts

            # Get all job numbers for this workflow:
            JOB_NUMBERS_CONTENT=$(curl --request GET \
              --url "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job" \
              --header "Circle-Token: ${CIRCLE_TOKEN}" \
              --header 'content-type: application/json')
            JOB_NUMBERS=$(echo $JOB_NUMBERS_CONTENT | jq -r '.items[] | select (.type? == "build") | .job_number')
            echo "Found job IDs in current workflow: $JOB_NUMBERS"

            # Get artifacts per each job:
            echo "Searching for Artifacts .........."
            for x in JOB_NUMBERS ; do 
              ART_CONTENT=$(curl --request GET \
                --url "https://circleci.com/api/v2/project/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/$x/artifacts" \
                --header "Circle-Token: ${CIRCLE_TOKEN}" \
                --header 'content-type: application/json') 
              ARTS=$(echo $ART_CONTENT | jq -r '.items[] | .url')
              echo 
              echo "*** Artifacts For Job Number $x ***"
              echo $ARTS
              echo 
            done

workflows:
  version: 2.1
  build:
    jobs:
      - build_ubuntu:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish_release:
          requires:
            - build_ubuntu
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/